export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  VERIFY_EMAIL: '/verify-email',
  SETTINGS: '/settings',
  MY_PUBLICATIONS: '/my-publications/:tab',
  ADD_PUBLICATION: '/add-publication',
  EDIT_PUBLICATION: '/edit-publication/:id',
  PUBLICATION: '/publication/:id',
  BOOKING: '/booking/:id/:tab',
  BOOKING_BASE: '/booking/:id',
  SEARCH_RESULTS: '/search-results',
  NOTIFICATIONS_BASE: '/notifications',
  NOTIFICATIONS: '/notifications/:id',
  PRIVACY_POLICY: '/privacy-policy',
  FAQ: '/faq',
  USER_PROFILE: '/profile',
  BOOKINGS_HISTORY: '/bookings-history',
  PUBLIC_USER_PROFILE: '/profile/:id',
  ADD_USER_INFO: '/add-user-info',
  NOT_FOUND: '/not-found',
};
