export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  VERIFY_EMAIL: '/verify-email',
  SETTINGS: '/settings',
  MY_PUBLICATIONS: '/my-publications',
  ADD_PUBLICATION: '/add-publication',
  EDIT_PUBLICATION: '/edit-publication/:id',
  PUBLICATION: '/publication/:id',
  SEARCH_RESULTS: '/search-results',
  NOTIFICATIONS: '/notifications',
  PAYMENT: '/payment',
  PRIVACY_POLICY: '/privacy-policy',
  FAQ: '/faq',
  USER_PROFILE: '/profile',
  PUBLIC_USER_PROFILE: '/profile/:id',
  ADD_USER_INFO: '/add-user-info',
  NOT_FOUND: '/not-found',
};
