export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTRATION: '/registration',
  VERIFICATION_CODE: '/verify-mobile',
  VERIFY_EMAIL: '/verify-email',
  SETTINGS: '/settings',
  PUBLICATIONS: '/publications',
  ADD_PUBLICATION: '/add-publication',
  ITEM: '/item/:id',
  SEARCH_RESULTS: '/search-results',
  USER_PROFILE: '/user-profile',
  NOTIFICATIONS: '/notifications',
  PAYMENT: '/payment',
  PRIVACY_POLICY: '/privacy-policy',
  FAQ: '/faq',
  ADD_USER_INFO: '/add-user-info',
  NOT_FOUND: '/not-found',
};
